### ISSUE TITLE
Logging API

### ISSUE THREAD

**Issue by chutchinson** [rpgtoolkit/editor#23]
The project is getting to a stage where logging is imperative. We need to choose a logging API. I recommend that we choose JSR47 (java.util.logging) to minimize dependencies; the built-in logging is also a facade so we could plug in something like Logback or log4j in the future.

http://logback.qos.ch/

**Comment by swordmaster2k** [comment]
I've put a very simple logger at the bottom of the UI for the moment that just pumps out the results of stdout to a JTextArea for debugging purposes. It would probably be a good idea to include this for any alpha and beta builds. In additional all logging should be wrote to an external timestamped file for each run so we can gather as much data as possible when a tester encounters a bug or crash.

![editor](https://cloud.githubusercontent.com/assets/3354016/8229922/3f740056-15b3-11e5-8786-8f42a91eb58d.png)

**Comment by chutchinson** [comment]
Sorry if this sounds rude, but that is not acceptable. I realize there is a sense of urgency to push this editor out, but a logging API is a relatively simple choice and we can do better. Besides the very start of the project, this is the perfect time to make the choice.

Here are some choices:
- JSR47 (java.util.logging)
- log4j
- Logback
- Apache Commons

I have already endorsed JSR47 and still think it's the best choice for this project. Almost any of those choices will allow you to provide a simple hook to intercept log messages and print them to a debug window, panel, file, etc.

**Comment by goblinJoel** [comment]
I don't think swordmaster meant his work as a permanent solution. He said, "a very simple logger at the bottom of the UI for the moment...for debugging purposes," and also that it would be good to have them write to files as well. I actually kind of like how his temporary logger keeps it in front of the developer who's testing the TK, but obviously we wouldn't want that in peoples' faces for release.

Swordmaster, what do you think of JSR47? I've never used any of these solutions, because I am a hack. :P

**Comment by swordmaster2k** [comment]
Euix, of course that is not a permanent implementation, I've already mentioned Log4j, Joel pointed out what I said. I've stuck that JTextArea in there as a concept which is particularly useful when I'm not dual screening as I can see the debug output while testing the UI. I got the idea from the Arduino IDE which contains a similar feature. It will be a useful for any testers that aren't familiar with running JAR's from consoles and examining output from there. Yes come release it would be disabled.

I'll look into JSR47 vs Log4j, which does have the advantage of not adding a dependency.

**Comment by chutchinson** [comment]
I understand the debug panel; it's a common user experience design pattern. I know it's not a permanent solution. This is a **crucial time** to choose a logging API because the project is getting large enough and has enough developers that logging is going to start becoming a serious implementation detail.  

I vote for JSR47 (java.util.logging) because I think it meets all of our needs. It supports levels, filtering, persistence to memory, standard input / output, files, and of course you can write a custom stream handler so you could intercept log messages and write them to a debug window. It avoids adding a runtime dependency. The downside to JSR47 is that it is minimal. It may not meet our debugging needs down the road. It honestly depends on how well we log messages.

I don't have a problem with log4j, logback, or almost anything else. We just need to agree on **something** before we get much deeper into development. Logback is a great alternative because it's the successor to log4j and is used in a great number of large open source projects (e.g. Gradle, Play Framework, Akka, etc). It's also a logging facade so you can plug in something more robust down the road.

http://logback.qos.ch/
http://logback.qos.ch/manual/introduction.html

**Comment by swordmaster2k** [comment]
Added logback support to the editor with an SLF4J implementation. The editor is at a minimum logging attempts to open and save assets. Any caught exceptions are logged to both STDOUT and a rolling file appender with INFO statements.

Format of the logs is controlled via the standard logback.xml in the resources folder. Will continue to expand amount of logging in the editor and implement something similar in core.

Will close this issue now.
