### ISSUE TITLE
Handling Boards Using Multiple Tilesets

### ISSUE THREAD

**Issue by swordmaster2k** [rpgtoolkit/editor#28]
Implement the ability to load multiple tilesets from a board into the 'Tileset' tab to the right of the editor. The current behaviour is to simply load the first tileset listed by the board and ignore all others. Instead what we want to do is load multiple tilesets. A maximum of 5 tilesets per board will be imposed, hopefully a user won't feel the need for anymore than that.

When a board is open, selected, or reselected the first tileset attached to that board will appear in the tileset tab, if it exists. The following user actions can be taken using the tileset tab:
- Select a tileset by left clicking on its tab entry.
- Modify a tileset by right clicking on its tab entry (i.e. switch it out for another)
- Remove a tileset from a board by middle clicking on its tab entry.
- Add a new tileset by clicking on the '+' to the right of all other tabs.

These controls are consistent with the rest of the board editor's features.

![20150808_195552](https://cloud.githubusercontent.com/assets/3354016/9151800/82c6e828-3e08-11e5-9c84-67057bcc8055.jpg)

**Comment by swordmaster2k** [comment]
Update: I've decided to go with a global TileSet palette that isn't bound to the current boards thus giving the user an endless possible number of TileSets used per board. However there will still be a restriction on the maximum number of sets that can be open in the palette.

**Comment by goblinJoel** [comment]
Sounds like a good feature.

**Comment by swordmaster2k** [comment]
Done. UI for this will be revised at polish time.
