### ISSUE TITLE
Project loads assets on open.

### ISSUE THREAD

**Issue by chutchinson** [rpgtoolkit/editor#5]
The game project should not load any auxiliary assets during open (such as the initial character, initial board, initial program, etc). References to these assets should be maintained in the Project class, and all other classes that reference other assets. 

Loading other assets during project load can cause the editor to fail prematurely because one of the assets within the project is corrupted. This extends to all similar files that reference assets.

**Comment by goblinJoel** [comment]
Is this something that's happening? I know I had it automatically opening project and then popping up another open dialog on launch for rapid testing, but I thought I'd avoided committing that.

It sounds like you're saying it's loading assets invisibly though, which probably means it's not my fault. :P _whew_

What is it loading?

**Comment by chutchinson** [comment]
At the moment it's loading the initial character, initial board, etc. It's basically loading every asset that a project file references. Absolutely not a good idea.

**Comment by swordmaster2k** [comment]
I believe that is Geoff legacy code, I can't remember why its there.

**Comment by swordmaster2k** [comment]
Project file format was loading the startup program, initial board, and initial characters in its constructor. It had no need to and I've changed them to string representations. 

Closed.
